// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"my-blog/app/dao/internal"
)

// adminsDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type adminsDao struct {
	*internal.AdminsDao
}

var (
	// Admin is globally public accessible object for table admins operations.
	Admin adminsDao
)

func init() {
	Admin = adminsDao{
		internal.NewAdminsDao(),
	}
}

// Fill with you ideas below.
