// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"my-blog/app/dao/internal"
)

// articlesDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type articlesDao struct {
	*internal.ArticlesDao
}

var (
	// Article is globally public accessible object for table articles operations.
	Article articlesDao
)

func init() {
	Article = articlesDao{
		internal.NewArticlesDao(),
	}
}

// Fill with you ideas below.
