// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// AdminsDao is the manager for logic model data accessing and custom defined data operations functions management.
type AdminsDao struct {
	gmvc.M               // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C      adminsColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.
	DB     gdb.DB        // DB is the raw underlying database management object.
	Table  string        // Table is the underlying table name of the DAO.
}

// AdminsColumns defines and stores column names for table admins.
type adminsColumns struct {
	Id        string //
	Username  string // 用户名
	Password  string // 密码
	CreatedAt string //
	UpdatedAt string //
}

// NewAdminsDao creates and returns a new DAO object for table data access.
func NewAdminsDao() *AdminsDao {
	columns := adminsColumns{
		Id:        "id",
		Username:  "username",
		Password:  "password",
		CreatedAt: "created_at",
		UpdatedAt: "updated_at",
	}
	return &AdminsDao{
		C:     columns,
		M:     g.DB("default").Model("admins").Safe(),
		DB:    g.DB("default"),
		Table: "admins",
	}
}
